INSERT INTO tags (id, tag) VALUES
   (0, 'Technology'),
   (1, 'Gaming'),
   (2, 'Entertainment'),
   (3, 'Lifestyle'),
   (4, 'Education'),
   (5, 'Community'),
   (6, 'Business'),
   (7, 'Hobbies'),
   (8, 'Science'),
   (9, 'Sports'),
   (10, 'Creative Arts'),
   (11, 'Politics'),
   (12, 'DIY & Crafting'),
   (13, 'Automobiles'),
   (14, 'Pets & Animals'),
   (15, 'Health & Wellness'),
   (16, 'Work & Productivity'),
   (17, 'Travel'),
   (18, 'Food & Drinks');